### ISSUE TITLE
Figure out if all the JS is needed?

### ISSUE THREAD

**Issue by Enkrona** [Enkrona/RAPTC#1]
So when we pushed the app to GitHub about 14,000 JavaScript files were uploaded as well. Let's figure out whether or not this is needed.

**Comment by Enkrona** [comment]
Remove unnecessary bloat created from default app, and unnecessary JavaScript.

**Comment by Wholinator** [comment]
Removed 133,811 files. May still be more to remove but the scourge of js has been ended
